fastlane_version "1.104.0"

default_platform :ios

platform :ios do

  desc "Setup carthage"
  lane :cart do
    sh "carthage update --platform iOS"
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "StartKitTests",
      clean: true,
      device: "iPhone 6",
      output_types: "html"
    )
  end

  desc "Setup profile"
  lane :build do
    match(git_url: "git@bitbucket.org:iossocket/iosstartkitmatchrepo.git",
      type: "adhoc",
      app_identifier: "com.thoughtworks.StartKit",
      readonly: true
    )
    gym(
      configuration: "Release",
      scheme: "StartKit",
      sdk: "iphoneos10.0",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "ad-hoc"
    )
  end

  desc "Deploy beta to hockeyapp"
  lane :deploy_beta do
    hockey(
      api_token: '2e6aadb3922b4f7182f970e4cc3bb9b7',
      ipa: './StartKit.ipa'
    )
  end

  desc "Test, build and deploy beta to hockeyapp"
  lane :beta do
    test
    build
    deploy_beta
  end

end
